// app/pages/index.jsx
import React from 'react';
import styled from 'styled-components';

import { Wave } from 'app/components/Curve';
import NavigationBar from 'app/components/NavigationBar';
import SKILLS from 'app/constants/skills';

export default function Home() {
    return <>
        <NavigationBar links={[
            ['#links', 'Links'],
            ['#skills', 'Skills'],
            ['/projects', 'Projects'],
        ]} />

        <Container>
            <Section color='#610909'>
                <Wave color='black' precent={100} />
                <h1>Apteryx</h1>
                <p>A Kiwi Software Developer</p>
            </Section>

            <Section id='links' color='#8c0f0f'>
                <Wave color='#610909' precent={125} />
                <h1>Link Tree</h1>
                <ButtonContainer>
                    <Button href='/discord' target='_blank'>Discord</Button>
                    <Button href='/github' target='_blank'>Github</Button>
                    <Button href='/youtube' target='_blank'>Youtube</Button>
                    <Button href='/twitter' target='_blank'>Twitter</Button>
                </ButtonContainer>
            </Section>

            <Section id='skills' color='#a12006'>
                <Wave color='#8c0f0f' precent={150} />
                <h1>Skills</h1>
                <SkillsGrid>
                    {SKILLS
                        .sort((a, b) => a[1].localeCompare(b[1]))
                        .map(([icon, name]) =>
                            <Skill key={name} icon={icon} name={name} />)}
                </SkillsGrid>
            </Section>
        </Container>
    </>
}

const Container = styled.div`
    display: flex;
    flex-direction: column;
    background-color: black;
`;

const Section = styled.section`
    position: relative;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    min-height: 400px;
    padding-top: 150px;
    color: white;
    background-color: ${props => props.color};

    h1 {
        max-width: 700px;
        text-align: center;
        font-size: 3rem;
        margin: 0;
    }

    p {
        max-width: 700px;
        text-align: center;
        font-size: 1.5rem;
        margin: 0;
    }
`;

const SkillsGrid = styled.div`
    display: grid;
    align-items: center;
    grid-template-columns: repeat(3, minmax(150px, 1fr));

    @media (max-width: 768px) {
        grid-template-columns: repeat(2, minmax(150px, 1fr));
    }
`;

const SkillContainer = styled.div`
    display: flex;
    flex-direction: row;
    align-items: center;
    font-size: 18px;
    padding: 5px;

    svg {
        margin-right: 2px;
    }
`;

function Skill({ icon, name }) {
    return <SkillContainer>
        {icon} {name}
    </SkillContainer>
}

const ButtonContainer = styled.div`
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
`;

const Button = styled.a`
    width: 100%;
    border-radius: 10px;
    padding: 10px;
    margin: 7px 0;
    background-color: #bf1717;
    text-align: center;
    cursor: pointer;
    transition: all 0.2s ease-in-out;

    &:hover {
        background-color: #ed1c1c;
    }
`;

// src/pages/index.vue
<script setup>
import timeline from '@/assets/data/timeline.json';
import skills from '@/assets/data/skills.json';
</script>

<template>
    <view>
        <Navbar />

        <div id="container" class="gradient">
            <section id="bio">
                <h1>Kia ora!</h1>

                <p>
                    Hey there, I'm Apteryx, a 17 year old software developer in the makings from
                    Aotearoa New Zealand.
                    <br />
                    <br />
                    I love to create things, anything from simple Discord bots to complex full stack
                    cross platform applications. View the
                    <NuxtLink to="/projects">projects</NuxtLink> page for a list of what I've been
                    up to.
                </p>

                <div id="socials">
                    <a href="https://discord.gg/vZQbMhwsKY" target="_blank">
                        <nuxt-icon name="discord" />
                    </a>
                    <a href="https://github.com/apteryxxyz" target="_blank">
                        <nuxt-icon name="github" />
                    </a>
                    <a href="https://twitter.com/apteryxxyz" target="_blank">
                        <nuxt-icon name="twitter" />
                    </a>
                    <a href="https://youtube.com/apteryx" target="_blank">
                        <nuxt-icon name="youtube" />
                    </a>
                </div>
            </section>

            <section id="journey">
                <h1>My Journey</h1>

                <div id="timeline">
                    <template v-for="(time, index) in timeline" :key="index">
                        <div>{{ time.frame }}</div>
                        <div>{{ time.text.join('\n') }}</div>
                    </template>
                </div>
            </section>

            <section id="skills">
                <h1>My Skillset</h1>

                <div id="languages">
                    <div v-for="(skill, index) in skills" :key="index">
                        <nuxt-icon :name="skill.icon" />
                        <span>{{ skill.name }}</span>
                    </div>
                </div>
            </section>
        </div>

        <Footer />
    </view>
</template>

<script>
export default {
    head: { title: 'Home' },
};
</script>

<style scoped>
#container {
    display: flex;
    flex-direction: column;
    height: 100%;
    align-items: center;
    justify-content: center;
    margin: auto 0;
    background-color: #181818;
    color: #fff;
}

#container section {
    display: flex;
    flex-direction: column;
    max-width: 700px;
    margin: 250px 10%;
}

#container section h1 {
    width: 100%;
    font-size: 2.5rem;
    font-weight: bold;
}

#container section p {
    font-size: 1.3rem;
}

#container section a {
    color: #fff;
    text-decoration: none;
    font-weight: bold;
}

#container section a:hover {
    color: #dfdfdf;
}

#socials {
    display: flex;
    flex-wrap: wrap;
}

#socials a {
    padding: 20px 10px 0 0;
    font-size: 32px;
    transition: all 0.2s ease-in-out;
}

#socials a:hover {
    color: #dfdfdf;
    transform: scale(1.1);
}

#timeline {
    display: grid;
    grid-template-columns: 10% 40% 10% 40%;
    white-space: pre-line;
}

#timeline div {
    display: flex;
    align-items: center;
    padding: 10px;
}

#timeline div:nth-child(odd) {
    text-align: center;
    justify-content: center;
    font-weight: bold;
    font-size: 1.5rem;
}

#timeline div:nth-child(even) {
    justify-content: flex-start;
}

#skills div {
    display: flex;
    flex-flow: row wrap;
    align-items: center;
    padding: 10px;
    font-size: 20px;
}

#skills div * {
    padding-right: 10px;
}

@media (max-width: 992px) {
    #timeline {
        grid-template-columns: 20% 80%;
    }
}

@media (max-width: 600px) {
    #container section {
        margin: 50px 10%;
    }

    #timeline {
        grid-template-columns: 1fr;
    }
}
</style>
