// src/pages/projects.vue
<script setup>
import projects from '@/assets/data/projects.json';
</script>

<template>
    <view>
        <Navbar />

        <div id="container" class="gradient">
            <div id="grid">
                <section v-for="(project, index) in projects" :key="index" class="project">
                    <h1>{{ project.name }}</h1>
                    <p>{{ project.description }}</p>

                    <div class="tech-group">
                        <div v-for="(tech, index2) in project.technologies" :key="index2">
                            <nuxt-icon :name="tech[0]" />
                            <span>{{ tech[1] }}</span>
                        </div>
                    </div>

                    <div class="button-group">
                        <template v-for="(button, index2) in project.buttons" :key="index2">
                            <a :href="button.url" :target="button.target">{{ button.text }}</a>
                        </template>
                    </div>
                </section>
            </div>
        </div>

        <Footer />
    </view>
</template>

<script>
export default {
    head: { title: 'Projects' },
};
</script>

<style scoped>
#container {
    display: flex;
    flex-direction: column;
    height: 100%;
    align-items: center;
    justify-content: center;
    margin: auto 0;
    background-color: #181818;
    color: #fff;
}

#grid {
    display: grid;
    grid-template-columns: 1fr 1fr 1fr;
    grid-gap: 20px;
    margin: 0 10%;
    white-space: pre-line;
}

#grid section {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    text-align: center;
    max-width: 500px;
    margin: 75px 10%;
}

#gris section h1 {
    width: 100%;
    font-size: 2.5rem;
    font-weight: bold;
}

#grid section p {
    font-size: 1.3rem;
}

@media (max-width: 1025px) {
    #grid {
        grid-template-columns: 1fr 1fr;
    }
}

@media (max-width: 769) {
    #grid {
        grid-template-columns: 1fr;
    }
}

.tech-group,
.button-group {
    padding-top: 25px;
    display: flex;
    font-size: 20px;
}

.tech-group div {
    padding: 20px;
}

.tech-group div * {
    padding-right: 10px;
}

.button-group a {
    margin: 7px;
    padding: 10px;
    text-align: center;
    border-radius: 10px;
    cursor: pointer;
    background-color: rgb(53 53 53);
    color: white;
    transition: all 0.2s ease-in-out;
}

.button-group a:hover {
    background-color: rgb(82 82 82);
}
</style>

// src/pages/projects.jsx
import React from 'react';
import styled from 'styled-components';

import { Wave } from '../components/Curve';
import NavigationBar from '../components/NavigationBar';
import PROJECTS from '../constants/projects';

export default function Projects() {
    return <>
        <NavigationBar links={[['/#links', 'Links'], ['/#skills', 'Skills'], ['/projects#top', 'Projects']]} />
        <Container id='top'>
            {PROJECTS
                .sort((a, b) => a.name.localeCompare(b.name))
                .map((project, i) => (<Section color={project.primaryColor}>
                    <Wave color={i === 0 ? 'black' : PROJECTS[i - 1].primaryColor} percent={(i + 1) * 100} />
                    <h1>{project.name}</h1>
                    <p>{project.description}</p>
                    <SkillsGrid>
                        {project.technologies
                            .sort((a, b) => a[1].localeCompare(b[1]))
                            .map(([icon, title]) => <Skill icon={icon} title={title} />)}
                    </SkillsGrid>

                    <ButtonContainer>
                        {project.buttons.map(button => (
                            <Button
                                key={button.href}
                                href={button.href}
                                target={button.target}
                                color={project.secondaryColor}
                                hoverColor={project.tertiaryColor}
                            >{button.text}</Button>
                        ))}
                    </ButtonContainer>
                </Section>))}
        </Container>
    </>
}

const Container = styled.div`
    display: flex;
    flex-direction: column;
    background-color: black;
`;

const Section = styled.section`
    position: relative;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    min-height: 400px;
    padding-top: 150px;
    color: white;
    background-color: ${props => props.color};

    h1 {
        max-width: 700px;
        text-align: center;
        font-size: 3rem;
        margin: 0;
    }

    p {
        max-width: 700px;
        text-align: center;
        font-size: 1.5rem;
        margin: 0;
    }
`;

const SkillsGrid = styled.div`
    display: grid;
    align-items: center;
    grid-template-columns: repeat(2, minmax(150px, 1fr));
`;

const SkillContainer = styled.div`
    display: flex;
    flex-direction: row;
    align-items: center;
    justify-content: center;
    font-size: 18px;
    padding: 5px;

    svg {
        margin-right: 2px;
    }
`;

function Skill({ icon, title }) {
    return <SkillContainer>
        {icon} {title}
    </SkillContainer>
}

const ButtonContainer = styled.div`
    display: flex;
    flex-direction: row;
    align-items: center;
    justify-content: center;
`;

const Button = styled.a`
    height: 100%;
    border-radius: 10px;
    padding: 10px;
    margin: 7px;
    background-color: ${props => props.color};
    text-align: center;
    cursor: pointer;
    transition: all 0.2s ease-in-out;

    &:hover {
        background-color: ${props => props.hoverColor};
    }
`;
